### PR TITLE
Adding track_creations, track_modifications, define_property, and define_constraint matchers

### PR DESCRIPTION
**Pull request by cheerfulstoic**

### CODE REVIEW

**Comment by cheerfulstoic** [comment]
Just added a simple `README` as well

**Comment by cheerfulstoic** [comment]
Awesome, thanks!  Are you planning on releasing as a gem to rubygems?

**Comment by sineed** [comment]
Sure, I'm sorry I thought that I will have more spare time to make this gem.

**Comment by sineed** [comment]
https://rubygems.org/gems/neo4j-rspec

**Pull request merged**
