### PR TITLE
Use RSpec DSL in HasN matchers

### PR DESCRIPTION
**Pull request by sineed**
related to #2

### CODE REVIEW

**Comment by sineed** [comment]
@cheerfulstoic I think it became more clear, what do you think?

**Comment by cheerfulstoic** [comment]
Yeah, I think it's improved, for sure.  It still feels a bit class-heavy.  In [the examples](https://relishapp.com/rspec/rspec-expectations/v/3-4/docs/custom-matchers/define-matcher-with-fluent-interface) they show basically using the `chain`s to set variable state and then evaluate it later, which is kind of what you're doing.  But obviously this is more complex and I don't know if putting all of the logic into the matcher would make sense or not.

As far as I'm concerned, though, I'm just happy that it works ;)

**Comment by sineed** [comment]
yes, but some variables need their own descriptions and matching logic so I decided to extract them into classes again =)

**Comment by cheerfulstoic** [comment]
Fair enough! ;)

**Pull request merged**
