### PR TITLE
Compatibility module

### PR DESCRIPTION
**Pull request by sineed**

### CODE REVIEW

**Comment by sineed** [comment]
@cheerfulstoic I'm not sure that it is good to use symbols for types in `define_property` matcher. Also I don't want user to specify the exact path to class, e.g. `Neo4j::Shared::Boolean` because I can be broken in the future releases. For now I use symbols.

Do you have any thoughts or suggestions about it?

**Comment by cheerfulstoic** [comment]
I was actually thinking that you just switch in the spec, but I :heart: that you made it a feature where everybody can just use `:Boolean` and it figures it out.

You might make your classes `Neo4jrb6` instead of `Neo4j6`.

One note is that you should be able to differentiate between >= 7.0.0 and < 7.0.0 which could allow support for versions before 6.  I don't know if anything else in this gem would break in versions 4/5, though.  Not necessary, just something to think about.

Great work!

**Comment by sineed** [comment]
I've renamed `Neo4j7` and `Neo4j6`. Also I tried to run test suite on 4 and 5 versions but had some errors.

I hope that there will be no users of `neo4j-rspec` with 4, 5 or lower versions of `neo4jrb`. If not then I will add another `Neo4jX` class.

**Comment by cheerfulstoic** [comment]
Yeah, I wouldn't worry too much about <= 5.  Seems good to me!

**Pull request merged**
