### PR TITLE
Update neo4jrb to 7th version; Update README and bump

### PR DESCRIPTION
**Pull request by sineed**

### CODE REVIEW

**Comment by sineed** [comment]
@cheerfulstoic I encountered some differencies between 6th and 7th versions of neo4j gem and decided to divide usage of matchers. 0.1.x branch will be for 6th version of neo4j while 0.2.x will be for 7th version.

**Comment by cheerfulstoic** [comment]
That's totally fine if you want to do that, though you could check the `Neo4j::VERSION` constant to determine the version and switch the constants in the spec accordingly.  The biggest advantage I see there is that you don't have to backport any improvements/changes that you make to 2.x back to 1.x

**Comment by sineed** [comment]
Yes I thought about that and I really don't know which strategy to accept. I don't like to add conditions based on the version of `neo4j` because it makes the code harder to read while using particular version of `neo4j` in different versions may lead to regular backports.

I hope that your advise is better because in the future there will be more matchers and I will need to copy the code to 0.1.x versions if I will use current implementation.

I will try to rewrite that moment. For now I leave this implementation.

**Comment by cheerfulstoic** [comment]
Cool ;)  Let me know if you would like any help!

**Pull request merged**
