### PR TITLE
Add define_index matcher

### PR DESCRIPTION
**Pull request by sineed**
@cheerfulstoic I have faced with an issue while implementing this matcher. Somehow the `index` option is not set on `DeclaredProperty` if I use `index :reserved` DSL. Although when I add an index through `property` method option then all is fine.

I have left failing test in the test suite and have made it pending.

Seems strange for me, maybe I do something wrong.

### CODE REVIEW

**Comment by cheerfulstoic** [comment]
Seems like a good question for @subvertallchris

Is there a good, consistent way to reflect on the indexes for a model?

**Comment by chrislgrigg** [comment]
The `DeclaredProperty` should be modified when calling the `index` property
property, it's intended to provide what you're looking for. If it's not
working, it should be an easy fix. I'll open an issue now.

**Comment by sineed** [comment]
As of https://github.com/neo4jrb/neo4j/pull/1146 there is no issue with the `index` class method.

I ran test suite against master branch of `neo4j` and saw the same problem with unset index option on attribute. That seems strange for me.
Also I tried to call `Neo4j::ActiveNode::Labels.clear_wrapped_models` before each spec but had no luck.

Continue to investigate this problem.

**Comment by sineed** [comment]
I found [this](https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/shared/declared_property/index.rb#L3) line and figured out that I need working Neo4j session for `index`method to work properly.

Sorry for disturbing you, guys

**Comment by cheerfulstoic** [comment]
Ah, nice, glad you figured that out!

One thing that I often do when trying to find the source of something is to run:

``` ruby
method(:index)
```

That will give me a [`Method`](http://ruby-doc.org/core-2.2.0/Method.html) object which I can then call `source_location` on like;

``` ruby
method(:index).source_location
```

which will give me the file path and line number of where the method is defined.

**Comment by sineed** [comment]
Thank you for your advice! I prefer using `pry` `$` notation, it also shows the body of inspected method, class or module:

``` ruby
pry> $ Person.index
```

**Pull request merged**
