### PR TITLE
only attempts to load matchers if RSpec has been defined

### LINKED ISSUE #18: Don't load matchers if RSpec does not exist
See https://github.com/sineed/neo4j-rspec/issues/15

### PR DESCRIPTION
**Pull request by capitalist**
This solves the problem in #15 and closes #18

### CODE REVIEW

**Comment by cheerfulstoic** [comment]
Thanks for this!  Should that condition be on the `neo4j/rspec/version` line as well?

The tests on this project are also currently failing with version 6.x of the `neo4j` gem.  If you update that to be testing against the lastest two major versions  (9.2.2 and 8.3.4) and the tests pass then I could merge this

**Comment by capitalist** [comment]
Yeah, I looked at the travis output. Those test failures are completely orthogonal to this change. If they get fixed, I'll rebase my commit onto the fix and push a new PR.

The conditional require isn't needed in the version file.

We just needed this to prevent errors on our CI environment and are installing from my fork at the moment.

**Comment by cheerfulstoic** [comment]
I've made the `master` CI green, so try merging in

**Comment by capitalist** [comment]
Nice job, it's all green now.

**Comment by cheerfulstoic** [comment]
:+1: Last question, should the `if Object.const_defined?(:RSpec)` also be on the `require 'neo4j/rspec/version'` line?

**Comment by cheerfulstoic** [comment]
Also, sorry, you'll need to merge again because I made a number of changes when I introduced `rubocop` into this gem

**Comment by capitalist** [comment]
It's not necessary to include the conditional on any other line.

**Comment by cheerfulstoic** [comment]
Oh, sorry, I see that you said that already ;(

Looks like CI is failing on some rubocop issues.  I'll fix them in `master`.   Thanks again!

**Comment by cheerfulstoic** [comment]
Released in 0.2.6

**Pull request merged**
